# render.yaml

services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        value: "mysql://root:aqpPBOExscQkWYqUPGQjQkpFJoIQlSPT@yamabiko.proxy.rlwy.net:26917/railway"

        
